# Generated by Django 2.2.1 on 2019-05-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190518_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(max_length=20, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(max_length=20, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(max_length=20, verbose_name='Assunto'),
        ),
    ]
